### PR TITLE
Custom theme directory

### PR DESCRIPTION
**Pull request by avently**
- user can add themes to ~/.config/deepin/deepin-terminal/themes with the same syntax as the default ones

### CODE REVIEW

**Comment by avently** [comment]
@manateelazycat is something wrong with this PR?

**Review by BLumia — APPROVED** [review]
Looks good!

**Comment by BLumia** [comment]
@hualet I don't have privilege to merge this PR on this repo, could you take a look? Thx.

**Comment by hualet** [comment]
@avently we need to move deepin-terminal from gerrit to github first, so that we can accept PRs, please wait a  little bit.

**Comment by hualet** [comment]
Building the infrastructure still takes some time, I've manually checked the build and the function, so I'll merge this now.

**Pull request merged**
